apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: contents-service-deployment
  labels:
    app: contents-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contents-service
  template:
    metadata:
      labels:
        app: contents-service
    spec:
      containers:
      - name: contents-service
        image: dtlabs/contents-service:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: MYSQL_DATABASE
          value: contents_db
        - name: MYSQL_PASSWORD
          value: ThePassword
        - name: MYSQL_USER
          value: labsflixuser
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "1Gi"
            cpu: "0.5"
